<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>tinspire</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(?i:(Prgm|EndPrgm|Func|EndFunc|If|Then|Else|ElseIf|For|While|Loop|Try|PassErr|Return|Cycle|Exit|Lbl|Goto|Stop|EndFor|EndTry|EndWhile|EndIf|EndLoop|Disp|Text))\b</string>
			<key>name</key>
			<string>keyword.control.tinspire</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.tinspire</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tinspire</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i:(Define))\b\s+(\w+(\.\w+)?)</string>
			<key>name</key>
			<string>meta.function.tinspire</string>
		</dict>
		<!-- <dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.tinspire</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tinspire</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i:())\b</string>
			<key>name</key>
			<string>support.function.tinspire</string>
		</dict> -->
		<dict>
			<key>match</key>
			<string>\b(getType|abs|amortTbl|and|angle|ANOVA|ANOVA2way|Ans|approx|arccos|arccosh|arccot|arccoth|arccsc|arccsch|arcLen|arcsec|arcsech|arcsin|arcsinh|arctan|arctanh|augment|avgRC)\b</string>
			<key>name</key>
			<string>support.function.tinspire</string>
		</dict>


		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.tinspire</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.tinspire</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(©).*$\n?</string>
			<key>name</key>
			<string>comment.symbol.tinspire.one</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.tinspire</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(©).*$\n?</string>
			<key>name</key>
			<string>comment.line.tinspire.two</string>
		</dict>
		<dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.tinspire</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.tinspire</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.tinspire</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
                    <key>name</key>
                    <string>constant.character.escape.tinspire</string>
                </dict>
            </array>
        </dict>
	</array>
	<key>scopeName</key>
	<string>source.tinspire</string>
	<key>uuid</key>
	<string>ddabc4ed-2790-45e0-8e55-31c8a2c14563</string>
</dict>
</plist>
